title = "GuestStatus: Smart Airbnb Monitoring | No Cameras, No Hassle."
baseURL = "https://www.gueststatus.com"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

defaultContentLanguage = "en"
#sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "GuestStatus"
# languageDirection = 'rtl' for Right-To-Left languages

[menu]
[[menu.main]]
name = 'Articles'
pageref = '/post'
weight = 2

[[menu.main]]
name = 'About'
pageref = '/about'
weight = 1

[[menu.main]]
name = 'Contact'
pageref = '/contact'
weight = 3

[[menu.main]]
name = 'Get Early Access →'
url = "/signup/"
identifier = "stripe-link"
weight = 4

[[menu.footer]]
name = "About"
url = "/about/"
weight = 10

[[menu.footer]]
name = "Services"
url = "/services/"
weight = 20

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 30


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = "black"
author = "GuestStatus Team" # default author, override via `author` in a posts front matter
favicon = "images/Gueststatus favicon.jpg"
site_logo = "images/Gueststatus logo 4-1.svg"
description = "The Smart, Affordable Solution for Airbnb Hosts to Manage Properties with Confidence."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
body_classes = "avenir"